### PR TITLE
Delete image squashed all commits

### LINKED ISSUE #8: Delete Image
#### As a user I want to delete an image.

Acceptance criteria:
- [ ] The user is prompted for confirmation prior to deletion.
- [ ] Deleted images are removed from the homepage.

Dependencies:
- Image Index

### PR DESCRIPTION
**Pull request by wilsonyqm**
Closes #8

### CODE REVIEW

**Comment by rmacklin** [comment]
Huh? I'm very confused by this PR. We already merged #27

**Comment by wilsonyqm** [comment]
Yep, I just squashed all the 7 commits into 2 commits and merge them again, as you mentioned that we didn't squash before we merge to master.

**Comment by rmacklin** [comment]
That doesn't make sense though... it was already merged. This PR was basically a no-op, other than cluttering the history even further.

**Comment by wilsonyqm** [comment]
I reset master to the head before we merge #27, and squash my local deleteImage into 2 commits, and merge this branch into master.

**Pull request merged**
